version: '3.3'
volumes:
  'virtdbnx-asp':
    driver: hpecv
    driver_opts:
      importVolAsClone: virtdbnxContext
      replStore: tme-staging-array2
      forceImport: "true"
services:
  virtdbnx:
    image: tmeregistry.azurecr.io/virtdbnx-asp
    build:
      context: .
      dockerfile: virtdbnx/Dockerfile_virtdbnx
    depends_on:
      - db
    ports:
      - '50938:80'
      - '2222:2222'
  db:
    image: tmeregistry.azurecr.io/virtdbnx-asp-db
    build:
      context: .
      dockerfile: virtdbnx_db/Dockerfile_virtdbnx_db
    environment:
      SA_PASSWORD: "My_P@ssw0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - '1410:1433'
    volumes:
      - virtdbnx-asp:/var/opt/mssql/sqldata/udb
